[package]
name = "extractor"
version = "1.0.1"
edition = "2024"

[dependencies]
binrw = "0.15.0"
clap = { version = "4.5.42", features = ["derive"] }
flate2 = { version = "1.1.2", features = ["zlib"] }
rayon = "1.10"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = 'abort'
