[package]
name = "extractor"
version = "1.0.0"
edition = "2024"

[dependencies]
flate2 = { version = "1.1.2", features = ["zlib"] }
rayon = "1.10"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = 'abort'
